print(royal_flush(player_cards))
# print(straight_flush(player_cards))
# print(four_of_a_kind(player_cards))
# print(full_house(player_cards))
# print(flush(player_cards))
# print(straight(player_cards))
# print(three_of_a_kind(player_cards))
# print(two_pairs(player_cards))
# print(one_pair(player_cards))
# print(player_rank(player_cards))